# Generated by Django 4.0.6 on 2022-08-13 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('movement_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_account', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('type_operation', models.TextField()),
                ('hour', models.DateField()),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('ac_type', models.TextField()),
            ],
            options={
                'db_table': 'tipo_cuenta',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
                ('type', models.TextField()),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cuentas.tipocuenta')),
            ],
            options={
                'db_table': 'cuenta',
            },
        ),
    ]
