# Generated by Django 4.1 on 2022-08-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='hour',
            field=models.CharField(max_length=200),
        ),
    ]
