# Generated by Django 4.0 on 2022-08-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_alter_movimientos_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='no_account',
            field=models.IntegerField(null=True),
        ),
    ]
