# Generated by Django 4.0.6 on 2022-08-13 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_brand', models.TextField()),
            ],
            options={
                'db_table': 'marca_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('card_number', models.TextField(unique=True)),
                ('cvv', models.TextField(db_column='CVV')),
                ('valid_from', models.DateField()),
                ('xpiration_date', models.DateField()),
                ('card_type', models.TextField()),
                ('cardbrand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarjetas.marcatarjeta')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
            options={
                'db_table': 'tarjeta',
            },
        ),
    ]
