# Generated by Django 4.0.6 on 2022-08-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0002_alter_prestamo_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='loan_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_type',
            field=models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('HIPOTECARIO', 'HIPOTECARIO'), ('PRENDARIO', 'PRENDARIO')], max_length=20),
        ),
    ]
