# Generated by Django 4.1 on 2022-08-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0003_alter_prestamo_loan_total_alter_prestamo_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='loan_total',
            field=models.IntegerField(),
        ),
    ]
